# Generated by Django 2.1 on 2019-03-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employee',
            new_name='employees',
        ),
    ]
